repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files #prevents giant files from being committed.
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: check-builtin-literals # requires literal syntax when initializing empty or zero python builtin types.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-json # checks json files for parseable syntax.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-xml # checks xml files for parseable syntax.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: sort-simple-yaml # sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
      - id: trailing-whitespace # trims trailing whitespace.
      - id: detect-private-key # Checks for the existence of private keys.
      - id: name-tests-test # Verifies that test files are named correctly.
        args: [--pytest-test-first]
  - repo: local
    hooks:
      - id: uv_sync
        name: UV Sync
        entry: uv sync
        pass_filenames: false
        language: system
        types: [python]
        stages: [post-checkout]
      - id: poe
        name: poe check
        entry: uv run poe check
        language: system
        types: [python]
